version: '3.8'

services:
  db_find_info:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: info_find
      MYSQL_USER: ducha
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/info_find.sql:/docker-entrypoint-initdb.d/info_find.sql
    restart: always

  backend:
    build: ./go_findinfo
    container_name: golang_backend
    ports:
      - "8080:8080"
    depends_on:
      - db_find_info
    environment:
      DB_HOST: db_find_info
      DB_USER: ducha
      DB_PASSWORD: 123456
      DB_NAME: info_find
      # Server
      PORT: 8080
      ENVIRONMENT: development

      # FE
      URL_FE: http://localhost:3000
      FRONTEND_REDIRECT_URL: http://localhost:3000/oauth-success

      #Google
      GOOGLE_REDIRECT_URL: http://localhost:8080/auth/callback
      GOOGLE_CLIENT_ID: 470576649745-cls4dp37n5ia2li1ddnaktqq4v9ijk6f.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_API_OAUTH: https://www.googleapis.com/oauth2/v2/userinfo
    restart: always

  frontend:
    build: ./reactJs_Basic
    container_name: react_frontend
    ports:
      - "3000:80"
    env_file:
      - ./reactJs_Basic/.env
    depends_on:
      - backend
    restart: always

volumes:
  db_data: